### ISSUE TITLE
`size_t` should be `uint` or `int`

### ISSUE THREAD

**Issue by gingerBill** [ThisDrunkDane/odin-imgui#1]
https://github.com/ThisDrunkDane/odin-dear_imgui/blob/a607c839357f71062d1cd3740a6e10b582c431c5/dear_imgui.odin#L157

**Comment by ThisDevDane** [comment]
but isn't uint and u64 the same size? so isn't it just a style preference?

**Comment by gingerBill** [comment]
Nope. `uint` on a 32-bit platform will be 32 bits. Also, show intent with your types.
