### ISSUE TITLE
Docking

### ISSUE THREAD

**Issue by NoahR02** [ThisDrunkDane/odin-imgui#13]
Would you be open to switching to the docking branch for cimgui? All we would have to do is switch the branch in the .gitmodules folder and write a few bindings for the new docking procedures.

This would let us do things like this:
![](https://user-images.githubusercontent.com/8225057/46304087-00035580-c5ae-11e8-8904-f27a9434574a.gif)
![](https://user-images.githubusercontent.com/4349811/46386974-e70eb780-c707-11e8-8583-be563ce3c11c.gif)

**Comment by sumofat** [comment]
Dont know why you closed this so quick but we are going to do this on a fork and also try to see what it will take to get support for the latest version of Imgui as well.
